name: craft-pytorch-env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.5.0  
      - torchvision==0.20.0
      - opencv-python==4.8.0.76 
      - scikit-image==0.21.0 
      - scipy==1.11.3 
